variables:
  ZOLA_VERSION: v0.8.0
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  image: centos:latest
  before_script: 
  - curl -L "https://github.com/getzola/zola/releases/download/${ZOLA_VERSION}/zola-${ZOLA_VERSION}-x86_64-unknown-linux-gnu.tar.gz" | tar -xz 
  script:
  - ./zola build
  artifacts:
    paths:
    - public