# The URL the site will be built for
base_url = "https://blog.masch.dev"
title = "masch.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "inspired-github"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

generate_rss = true

theme = "even"

taxonomies = [
    {name = "tags", rss = true},
]

[extra]
even_title = "masch.dev"
# Put all your custom variables here
even_menu = [
    #{url = "$BASE_URL", name = "Home"},
    #{url = "$BASE_URL/blog/", name = "Blog"},
    #{url = "$BASE_URL/tags", name = "Tags"},
    #{url = "$BASE_URL/about", name = "About"},
]
